name: hourly

on:
  workflow_dispatch:
  schedule:
    - cron: '11 6 * * *'

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }},
          ENTSOE_API: ${{ secrets.ENTSOE_API }}
        run: |
          cd notebooks
          jupyter nbconvert --to notebook --execute pipeline.ipynb
          jupyter nbconvert --to notebook --execute inference.ipynb
          echo "Finished executing notebooks."
          echo "Checking for files in IMAGES"
          ls -la Images/

      - name: Verify modified files with git status
        run: git status

      - name: github pages publish
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Predictions published"
          commit_options: '--no-verify --signoff'

          file_pattern: 'Images/*'

          repository: .

          status_options: '--untracked-files=no'

          skip_dirty_check: true

          skip_fetch: true

          skip_checkout: true

          push_options: '--force'
